language: ruby
before_install:
 - gem install bundler --no-doc
 - sudo apt-get update -qq
 - sudo apt-get install -y protobuf-compiler
cache: bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
